### ISSUE TITLE
Ignore limit value if <= 0

### ISSUE THREAD

**Issue by LordTuxn** [AlpsBTE/Plot-System-API#18]
For example ignore limit if route is `get_plots?limit=-1` or `get_plots?limit=0`

**Comment by jokil123** [comment]
easy fix would be to just change the expected datatype from i32 to u32, limit zero would still be possible though. I think allowing 0 is okay and the user should get zero elements if he request so, instead of an error.

**Comment by jokil123** [comment]
The value is currently ignored, but the default value is all, I will change the default value to 20, or should this be configurable?
